MyRepo:
  Type: AWS::CodeCommit::Repository
  Properties:
    RepositoryName: express-app
    RepositoryDescription: simple express app to check health point

MyEC2Instance:
  Type: AWS::EC2::Instance
  Properties:
    InstanceType: t2.micro
    ImageId: ami-0c55b159cbfafe1f0

ArtifactBucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: cc-cb-cd-ec2

MyPipeline:
  Type: AWS::CodePipeline::Pipeline
  Properties:
    Name: ec2-ci-cd-pipeline
    ArtifactStore: 
      Type: S3
      Location: !Ref ArtifactBucket
    Stages: 
      - Name: Source
        Actions: 
          Name: SourceAction
          ActionTypeId:
            Category: Source
            Owner: AWS
            Version: 1
            Provider: CodeCommit
          OutputArtifacts:
            - Name: SourceOutput
          Configuration:
            S3Bucket:
              Ref: ArtifactBucket
            S3ObjectKey:
              Ref: SourceArtifacts
      - Name: Build
        Actions: 
          Name: BuildAction
          InputArtifacts:
            - Name: SourceOutput
          ActionTypeId:
            Category: Build
            Owner: AWS
            Version: 1
            Provider: CodeBuild
          OutputArtifacts:
            - Name: BuildOutput
          Configuration:
            S3Bucket:
              Ref: ArtifactBucket
            S3ObjectKey:
              Ref: BuildArtifacts
      - Name: Deploy
        Actions: 
          Name: DeployAction
          InputArtifacts:
            - Name: BuildOutput
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Version: 1
            Provider: CodeDeploy
          OutputArtifacts:
            - Name: DeployOutput
          Configuration:
            S3Bucket:
              Ref: ArtifactBucket
            S3ObjectKey:
              Ref: DeployArtifacts